const users = [
  { id: 1, name: "Arif Rahman", email: "arif.rahman@gmail.com", password: "pass123", phone: "01711000001", age: 24, city: "Dhaka", profession: "Web Developer", status: "Active" },
  { id: 2, name: "Nusrat Jahan", email: "nusrat.jahan@gmail.com", password: "pass123", phone: "01811000002", age: 22, city: "Chittagong", profession: "Graphic Designer", status: "Active" },
  { id: 3, name: "Sakib Hasan", email: "sakib.hasan@gmail.com", password: "pass123", phone: "01911000003", age: 27, city: "Rajshahi", profession: "Software Engineer", status: "Active" },
  { id: 4, name: "Mim Akter", email: "mim.akter@gmail.com", password: "pass123", phone: "01611000004", age: 21, city: "Sylhet", profession: "Student", status: "Inactive" },
  { id: 5, name: "Tanvir Ahmed", email: "tanvir.ahmed@gmail.com", password: "pass123", phone: "01711000005", age: 29, city: "Dhaka", profession: "Accountant", status: "Active" },
  { id: 6, name: "Fahim Rahman", email: "fahim.rahman@gmail.com", password: "pass123", phone: "01811000006", age: 26, city: "Khulna", profession: "Teacher", status: "Active" },
  { id: 7, name: "Jannatul Ferdous", email: "jannatul.ferdous@gmail.com", password: "pass123", phone: "01911000007", age: 23, city: "Barisal", profession: "Nurse", status: "Inactive" },
  { id: 8, name: "Rakib Hossain", email: "rakib.hossain@gmail.com", password: "pass123", phone: "01611000008", age: 31, city: "Dhaka", profession: "Businessman", status: "Active" },
  { id: 9, name: "Sumaiya Islam", email: "sumaiya.islam@gmail.com", password: "pass123", phone: "01711000009", age: 25, city: "Rangpur", profession: "Content Creator", status: "Active" },
  { id: 10, name: "Mahmudul Hasan", email: "mahmudul.hasan@gmail.com", password: "pass123", phone: "01811000010", age: 28, city: "Mymensingh", profession: "Banker", status: "Active" },
  { id: 11, name: "Tanjim Ahmed", email: "tanjim.ahmed@gmail.com", password: "pass123", phone: "01911000011", age: 24, city: "Dhaka", profession: "Programmer", status: "Inactive" },
  { id: 12, name: "Sadia Afrin", email: "sadia.afrin@gmail.com", password: "pass123", phone: "01611000012", age: 22, city: "Chittagong", profession: "Doctor", status: "Active" },
  { id: 13, name: "Imran Khan", email: "imran.khan@gmail.com", password: "pass123", phone: "01711000013", age: 30, city: "Rajshahi", profession: "Civil Engineer", status: "Active" },
  { id: 14, name: "Raisa Islam", email: "raisa.islam@gmail.com", password: "pass123", phone: "01811000014", age: 23, city: "Sylhet", profession: "Designer", status: "Active" },
  { id: 15, name: "Shakil Ahmed", email: "shakil.ahmed@gmail.com", password: "pass123", phone: "01911000015", age: 27, city: "Khulna", profession: "Developer", status: "Inactive" },
  { id: 16, name: "Mahi Rahman", email: "mahi.rahman@gmail.com", password: "pass123", phone: "01611000016", age: 20, city: "Dhaka", profession: "Student", status: "Active" },
  { id: 17, name: "Nayeem Hossain", email: "nayeem.hossain@gmail.com", password: "pass123", phone: "01711000017", age: 26, city: "Rangpur", profession: "Photographer", status: "Active" },
  { id: 18, name: "Faria Akter", email: "faria.akter@gmail.com", password: "pass123", phone: "01811000018", age: 24, city: "Barisal", profession: "Teacher", status: "Inactive" },
  { id: 19, name: "Rafiul Islam", email: "rafiul.islam@gmail.com", password: "pass123", phone: "01911000019", age: 29, city: "Dhaka", profession: "Marketing Manager", status: "Active" },
  { id: 20, name: "Anika Sultana", email: "anika.sultana@gmail.com", password: "pass123", phone: "01611000020", age: 22, city: "Mymensingh", profession: "Writer", status: "Active" },
  { id: 21, name: "Hasan Mahmud", email: "hasan.mahmud@gmail.com", password: "pass123", phone: "01711000021", age: 32, city: "Dhaka", profession: "Businessman", status: "Active" },
  { id: 22, name: "Tisha Rahman", email: "tisha.rahman@gmail.com", password: "pass123", phone: "01811000022", age: 21, city: "Chittagong", profession: "Student", status: "Inactive" },
  { id: 23, name: "Adnan Karim", email: "adnan.karim@gmail.com", password: "pass123", phone: "01911000023", age: 28, city: "Rajshahi", profession: "Software Engineer", status: "Active" },
  { id: 24, name: "Puja Das", email: "puja.das@gmail.com", password: "pass123", phone: "01611000024", age: 25, city: "Sylhet", profession: "Architect", status: "Active" },
  { id: 25, name: "Riyad Hossain", email: "riyad.hossain@gmail.com", password: "pass123", phone: "01711000025", age: 30, city: "Khulna", profession: "Manager", status: "Inactive" },
  { id: 26, name: "Sanjida Akter", email: "sanjida.akter@gmail.com", password: "pass123", phone: "01811000026", age: 23, city: "Dhaka", profession: "UI Designer", status: "Active" },
  { id: 27, name: "Mehedi Hasan", email: "mehedi.hasan@gmail.com", password: "pass123", phone: "01911000027", age: 27, city: "Rangpur", profession: "Cyber Security", status: "Active" },
  { id: 28, name: "Sharmin Jahan", email: "sharmin.jahan@gmail.com", password: "pass123", phone: "01611000028", age: 26, city: "Barisal", profession: "HR Manager", status: "Inactive" },
  { id: 29, name: "Arafat Rahman", email: "arafat.rahman@gmail.com", password: "pass123", phone: "01711000029", age: 24, city: "Dhaka", profession: "App Developer", status: "Active" },
  { id: 30, name: "Labiba Islam", email: "labiba.islam@gmail.com", password: "pass123", phone: "01811000030", age: 22, city: "Mymensingh", profession: "Teacher", status: "Active" },
  { id: 31, name: "Shuvo Ahmed", email: "shuvo.ahmed@gmail.com", password: "pass123", phone: "01911000031", age: 29, city: "Chittagong", profession: "Photographer", status: "Active" },
  { id: 32, name: "Nabila Rahman", email: "nabila.rahman@gmail.com", password: "pass123", phone: "01611000032", age: 24, city: "Dhaka", profession: "Data Analyst", status: "Inactive" },
  { id: 33, name: "Omar Faruk", email: "omar.faruk@gmail.com", password: "pass123", phone: "01711000033", age: 33, city: "Rajshahi", profession: "Doctor", status: "Active" },
  { id: 34, name: "Mousumi Akter", email: "mousumi.akter@gmail.com", password: "pass123", phone: "01811000034", age: 27, city: "Sylhet", profession: "Accountant", status: "Active" },
  { id: 35, name: "Jahid Hasan", email: "jahid.hasan@gmail.com", password: "pass123", phone: "01911000035", age: 25, city: "Khulna", profession: "Web Designer", status: "Inactive" },
  { id: 36, name: "Sabrina Islam", email: "sabrina.islam@gmail.com", password: "pass123", phone: "01611000036", age: 23, city: "Dhaka", profession: "Content Writer", status: "Active" },
  { id: 37, name: "Farhan Ahmed", email: "farhan.ahmed@gmail.com", password: "pass123", phone: "01711000037", age: 28, city: "Rangpur", profession: "Network Engineer", status: "Active" },
  { id: 38, name: "Rumana Jahan", email: "rumana.jahan@gmail.com", password: "pass123", phone: "01811000038", age: 26, city: "Barisal", profession: "Lawyer", status: "Inactive" },
  { id: 39, name: "Saif Hasan", email: "saif.hasan@gmail.com", password: "pass123", phone: "01911000039", age: 30, city: "Dhaka", profession: "Entrepreneur", status: "Active" },
  { id: 40, name: "Tasmia Rahman", email: "tasmia.rahman@gmail.com", password: "pass123", phone: "01611000040", age: 21, city: "Mymensingh", profession: "Student", status: "Active" },
  { id: 41, name: "Asif Iqbal", email: "asif.iqbal@gmail.com", password: "pass123", phone: "01711000041", age: 31, city: "Chittagong", profession: "Business Analyst", status: "Active" },
  { id: 42, name: "Lamia Akter", email: "lamia.akter@gmail.com", password: "pass123", phone: "01811000042", age: 24, city: "Rajshahi", profession: "Nurse", status: "Inactive" },
  { id: 43, name: "Rashed Karim", email: "rashed.karim@gmail.com", password: "pass123", phone: "01911000043", age: 29, city: "Dhaka", profession: "Software Developer", status: "Active" },
  { id: 44, name: "Mariya Sultana", email: "mariya.sultana@gmail.com", password: "pass123", phone: "01611000044", age: 22, city: "Sylhet", profession: "Graphic Designer", status: "Active" },
  { id: 45, name: "Touhid Ahmed", email: "touhid.ahmed@gmail.com", password: "pass123", phone: "01711000045", age: 27, city: "Khulna", profession: "System Administrator", status: "Inactive" },
  { id: 46, name: "Sohana Rahman", email: "sohana.rahman@gmail.com", password: "pass123", phone: "01811000046", age: 25, city: "Dhaka", profession: "Digital Marketer", status: "Active" },
  { id: 47, name: "Noman Hossain", email: "noman.hossain@gmail.com", password: "pass123", phone: "01911000047", age: 30, city: "Rangpur", profession: "Engineer", status: "Active" },
  { id: 48, name: "Ishrat Jahan", email: "ishrat.jahan@gmail.com", password: "pass123", phone: "01611000048", age: 23, city: "Barisal", profession: "Researcher", status: "Inactive" },
  { id: 49, name: "Munna Ahmed", email: "munna.ahmed@gmail.com", password: "pass123", phone: "01711000049", age: 28, city: "Dhaka", profession: "Full Stack Developer", status: "Active" },
  { id: 50, name: "Samia Islam", email: "samia.islam@gmail.com", password: "pass123", phone: "01811000050", age: 24, city: "Mymensingh", profession: "UI/UX Designer", status: "Active" }
];